languageCode:           "en"
title:                  "CoreUI"
baseURL:                "https://coreui.io/docs/5.0-alpha/"
canonifyURLs:           true

security:
  enableInlineShortcodes: true
  funcs:
    getenv:
      - ^HUGO_
      - NETLIFY

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "term", "RSS"]

publishDir:             "_gh_pages"

module:
  mounts:
    - source:           dist
      target:           static/dist
    - source:           docs/assets
      target:           assets
    - source:           docs/content
      target:           content
    - source:           docs/data
      target:           data
    - source:           docs/layouts
      target:           layouts
    - source:           docs/static
      target:           static
    - source:           docs/static/assets/img/favicons/apple-touch-icon.png
      target:           static/apple-touch-icon.png
    - source:           docs/static/assets/img/favicons/favicon.ico
      target:           static/favicon.ico

params:
  description:          "Open Source Ui Components library built on top of Bootstrap 5."
  authors:              "Lukasz Holeczek, Andrzej Kopanski"
  social_image_path:    /assets/brand/coreui-social.jpg
  social_logo_path:     /assets/brand/coreui-social-logo.png

  current_version:      "5.0.0-alpha.0"
  current_ruby_version: "5.0.0-alpha.0"
  docs_version:         "4.1"
  rfs_version:          "9.0.3"
  github_org:           "https://github.com/coreui/coreui"
  repo:                 "https://github.com/coreui/coreui"
  twitter:              "core_ui"
  opencollective:       "coreui"
  community:            "https://github.com/coreui/coreui/discussions"
  blog:                 "https://coreui.io/blog/"
  icons:                "https://icons.coreui.io/"

  download:
    source:             "https://github.com/coreui/coreui/archive/v5.0.0-alpha.0.zip"
    dist:               "https://github.com/coreui/coreui/releases/download/v5.0.0-alpha.0/coreui-5.0.0-alpha.0-dist.zip"

  download_template:
    website:            "https://coreui.io/product/free-bootstrap-admin-template/"

  cdn:
  # See https://www.srihash.org for info on how to generate the hashes
    css:             "https://cdn.jsdelivr.net/npm/@coreui/coreui@5.0.0-alpha.0/dist/css/coreui.min.css"
    css_hash:        "sha384-7VsCeBiBWz5u6Ew7EQ0ltuCAjFILOzpRyDq99FIonEeQvYtRsf4wm6YNgG8Q5bsi"
    css_rtl:         "https://cdn.jsdelivr.net/npm/@coreui/coreui@5.0.0-alpha.0/dist/css/coreui.rtl.min.css"
    css_rtl_hash:    "sha384-mSQsYL9pTOqWHgQBF35DEdSMuob4LFyQhqQpTD97QSRTEkesO31mFqAcnGUp8MNB"
    js:              "https://cdn.jsdelivr.net/npm/@coreui/coreui@5.0.0-alpha.0/dist/js/coreui.min.js"
    js_hash:         "sha384-7W3SZx4qHE4CTLi6GJX0NxXHNDQ2Y2sDLYh07CVHTI0DvxGEgFhc5ECY2icr44YW"
    js_bundle:       "https://cdn.jsdelivr.net/npm/@coreui/coreui@5.0.0-alpha.0/dist/js/coreui.bundle.min.js"
    js_bundle_hash:  "sha384-PLhwnmvmluev7VY5wxkP85r/G3Ixgr/X2wDsxnKqjd8hfSllb9CS/FE2Z8/WXEPF"
    popper:           "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
    popper_hash:      "sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
